source "https://rubygems.org"

gem "jekyll", "~> 4.2.0"
gem "jekyll-sitemap"
gem "jekyll-gist"
gem 'jekyll-mentions'
gem 'jekyll-feed'
gem 'jekyll-paginate'

# this restricts jekyll to functioning like it would on github pages
# gem 'github-pages', group: :jekyll_plugins

# gem 'jekyll-maps'
gem 'jekyll-scholar'
